// Code generated by gen_client. DO NOT EDIT.
package client

import (
	"github.com/chippydip/go-sc2ai/api"
)

func (c *connection) createGame(createGame api.RequestCreateGame) func() (*api.ResponseCreateGame, error) {
	f := c.request(&api.Request{
		Request: &api.Request_CreateGame{
			CreateGame: &createGame,
		},
	})
	return func() (*api.ResponseCreateGame, error) {
		r, err := f()
		return r.GetCreateGame(), err
	}
}

func (c *connection) joinGame(joinGame api.RequestJoinGame) func() (*api.ResponseJoinGame, error) {
	f := c.request(&api.Request{
		Request: &api.Request_JoinGame{
			JoinGame: &joinGame,
		},
	})
	return func() (*api.ResponseJoinGame, error) {
		r, err := f()
		return r.GetJoinGame(), err
	}
}

func (c *connection) restartGame(restartGame api.RequestRestartGame) func() (*api.ResponseRestartGame, error) {
	f := c.request(&api.Request{
		Request: &api.Request_RestartGame{
			RestartGame: &restartGame,
		},
	})
	return func() (*api.ResponseRestartGame, error) {
		r, err := f()
		return r.GetRestartGame(), err
	}
}

func (c *connection) startReplay(startReplay api.RequestStartReplay) func() (*api.ResponseStartReplay, error) {
	f := c.request(&api.Request{
		Request: &api.Request_StartReplay{
			StartReplay: &startReplay,
		},
	})
	return func() (*api.ResponseStartReplay, error) {
		r, err := f()
		return r.GetStartReplay(), err
	}
}

func (c *connection) leaveGame(leaveGame api.RequestLeaveGame) func() (*api.ResponseLeaveGame, error) {
	f := c.request(&api.Request{
		Request: &api.Request_LeaveGame{
			LeaveGame: &leaveGame,
		},
	})
	return func() (*api.ResponseLeaveGame, error) {
		r, err := f()
		return r.GetLeaveGame(), err
	}
}

func (c *connection) quickSave(quickSave api.RequestQuickSave) func() (*api.ResponseQuickSave, error) {
	f := c.request(&api.Request{
		Request: &api.Request_QuickSave{
			QuickSave: &quickSave,
		},
	})
	return func() (*api.ResponseQuickSave, error) {
		r, err := f()
		return r.GetQuickSave(), err
	}
}

func (c *connection) quickLoad(quickLoad api.RequestQuickLoad) func() (*api.ResponseQuickLoad, error) {
	f := c.request(&api.Request{
		Request: &api.Request_QuickLoad{
			QuickLoad: &quickLoad,
		},
	})
	return func() (*api.ResponseQuickLoad, error) {
		r, err := f()
		return r.GetQuickLoad(), err
	}
}

func (c *connection) quit(quit api.RequestQuit) func() (*api.ResponseQuit, error) {
	f := c.request(&api.Request{
		Request: &api.Request_Quit{
			Quit: &quit,
		},
	})
	return func() (*api.ResponseQuit, error) {
		r, err := f()
		return r.GetQuit(), err
	}
}

func (c *connection) gameInfo(gameInfo api.RequestGameInfo) func() (*api.ResponseGameInfo, error) {
	f := c.request(&api.Request{
		Request: &api.Request_GameInfo{
			GameInfo: &gameInfo,
		},
	})
	return func() (*api.ResponseGameInfo, error) {
		r, err := f()
		return r.GetGameInfo(), err
	}
}

func (c *connection) observation(observation api.RequestObservation) func() (*api.ResponseObservation, error) {
	f := c.request(&api.Request{
		Request: &api.Request_Observation{
			Observation: &observation,
		},
	})
	return func() (*api.ResponseObservation, error) {
		r, err := f()
		return r.GetObservation(), err
	}
}

func (c *connection) action(action api.RequestAction) func() (*api.ResponseAction, error) {
	f := c.request(&api.Request{
		Request: &api.Request_Action{
			Action: &action,
		},
	})
	return func() (*api.ResponseAction, error) {
		r, err := f()
		return r.GetAction(), err
	}
}

func (c *connection) obsAction(obsAction api.RequestObserverAction) func() (*api.ResponseObserverAction, error) {
	f := c.request(&api.Request{
		Request: &api.Request_ObsAction{
			ObsAction: &obsAction,
		},
	})
	return func() (*api.ResponseObserverAction, error) {
		r, err := f()
		return r.GetObsAction(), err
	}
}

func (c *connection) step(step api.RequestStep) func() (*api.ResponseStep, error) {
	f := c.request(&api.Request{
		Request: &api.Request_Step{
			Step: &step,
		},
	})
	return func() (*api.ResponseStep, error) {
		r, err := f()
		return r.GetStep(), err
	}
}

func (c *connection) data(data api.RequestData) func() (*api.ResponseData, error) {
	f := c.request(&api.Request{
		Request: &api.Request_Data{
			Data: &data,
		},
	})
	return func() (*api.ResponseData, error) {
		r, err := f()
		return r.GetData(), err
	}
}

func (c *connection) query(query api.RequestQuery) func() (*api.ResponseQuery, error) {
	f := c.request(&api.Request{
		Request: &api.Request_Query{
			Query: &query,
		},
	})
	return func() (*api.ResponseQuery, error) {
		r, err := f()
		return r.GetQuery(), err
	}
}

func (c *connection) saveReplay(saveReplay api.RequestSaveReplay) func() (*api.ResponseSaveReplay, error) {
	f := c.request(&api.Request{
		Request: &api.Request_SaveReplay{
			SaveReplay: &saveReplay,
		},
	})
	return func() (*api.ResponseSaveReplay, error) {
		r, err := f()
		return r.GetSaveReplay(), err
	}
}

func (c *connection) replayInfo(replayInfo api.RequestReplayInfo) func() (*api.ResponseReplayInfo, error) {
	f := c.request(&api.Request{
		Request: &api.Request_ReplayInfo{
			ReplayInfo: &replayInfo,
		},
	})
	return func() (*api.ResponseReplayInfo, error) {
		r, err := f()
		return r.GetReplayInfo(), err
	}
}

func (c *connection) availableMaps(availableMaps api.RequestAvailableMaps) func() (*api.ResponseAvailableMaps, error) {
	f := c.request(&api.Request{
		Request: &api.Request_AvailableMaps{
			AvailableMaps: &availableMaps,
		},
	})
	return func() (*api.ResponseAvailableMaps, error) {
		r, err := f()
		return r.GetAvailableMaps(), err
	}
}

func (c *connection) saveMap(saveMap api.RequestSaveMap) func() (*api.ResponseSaveMap, error) {
	f := c.request(&api.Request{
		Request: &api.Request_SaveMap{
			SaveMap: &saveMap,
		},
	})
	return func() (*api.ResponseSaveMap, error) {
		r, err := f()
		return r.GetSaveMap(), err
	}
}

func (c *connection) ping(ping api.RequestPing) func() (*api.ResponsePing, error) {
	f := c.request(&api.Request{
		Request: &api.Request_Ping{
			Ping: &ping,
		},
	})
	return func() (*api.ResponsePing, error) {
		r, err := f()
		return r.GetPing(), err
	}
}

func (c *connection) debug(debug api.RequestDebug) func() (*api.ResponseDebug, error) {
	f := c.request(&api.Request{
		Request: &api.Request_Debug{
			Debug: &debug,
		},
	})
	return func() (*api.ResponseDebug, error) {
		r, err := f()
		return r.GetDebug(), err
	}
}
