// Code generated by gen_ids. DO NOT EDIT.
package effect

import "github.com/chippydip/go-sc2ai/api"

const (
	Invalid                    api.EffectID = 0
	PsiStorm                   api.EffectID = 1
	GuardianShield             api.EffectID = 2
	TemporalFieldGrowing       api.EffectID = 3
	TemporalField              api.EffectID = 4
	ThermalLance               api.EffectID = 5
	ScannerSweep               api.EffectID = 6
	NukeDot                    api.EffectID = 7
	LiberatorDefenderZoneSetup api.EffectID = 8
	LiberatorDefenderZone      api.EffectID = 9
	BlindingCloud              api.EffectID = 10
	CorrosiveBile              api.EffectID = 11
	LurkerSpines               api.EffectID = 12
)
